# Generated by Django 3.2.4 on 2021-06-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('day', models.DateTimeField(auto_now_add=True)),
                ('reminder', models.BooleanField(default=False)),
            ],
        ),
    ]
