# Generated by Django 3.2.4 on 2021-06-20 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='todo',
            name='time',
            field=models.TimeField(default=django.utils.timezone.localtime),
        ),
    ]
