# Generated by Django 3.2.4 on 2021-06-18 09:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_todo_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='day',
        ),
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='todo',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
