# Generated by Django 3.2.4 on 2021-06-20 09:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210620_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='todo',
            name='time',
            field=models.TimeField(blank=True, default=django.utils.timezone.localtime),
        ),
    ]
